### PR TITLE
Convert to using a service that triggers events for component

### PR DESCRIPTION
**Pull request by dasnixon**
Since Ember is moving away from using controllers, having a service
that can broadcast events you can listen to from anywhere seems
useful.

@jerel let me know what you think, I can update the README with the updated functionality if we think this is worth it. Just me playing around, a super cool library nonetheless!

### CODE REVIEW

**Comment by jerel** [comment]
@dasnixon I like this direction. Lots of different types of code may want to trigger the slider (such as a component that uses the `store`). 

One thing I noticed, it appears that the ability to set `speed`, `color`, etc via the component attributes was removed? I believe it'd be best to keep that for backwards compatibility and template usage.

**Comment by dasnixon** [comment]
@jerel I'll re-add that functionality back to make it backwards compatible. Probably get to it on Friday.

**Comment by jerel** [comment]
@dasnixon ping :-)

**Comment by dasnixon** [comment]
@jerel sorry got a little busy, will get to this soon though.

**Comment by dasnixon** [comment]
@jerel updated, let me know if it looks good.

**Comment by dasnixon** [comment]
ping @jerel

**Comment by jerel** [comment]
@dasnixon thanks so much for this contribution!

**Pull request merged**
